### ISSUE TITLE
junit.xml empty report

### ISSUE THREAD

**Issue by rascio** [lambdaisland/kaocha-junit-xml#4]
Here a [project](https://github.com/lambdaisland/kaocha-junit-xml/files/2796574/kaocha-junit-test.zip) with the issue.

In the `tests.edn` configuration I've enabled the `kaocha-junit-xml` plugin, but when I execute the tests using:
```
lein repl
user=> (use 'kaocha.repl)
nil
user=> (run :unit)
```

It creates a "poor" detailed report for failures in the `target/test-reports/junit.xml`, like:

    <?xml version='1.0' encoding='UTF-8'?>
    <testsuites>
    <testsuite errors="1" package="" tests="3" name="unit" time="0.000000" hostname="localhost" id="0" timestamp="2019-01-25T14:56:16" failures="3">
    <properties/>
    <system-out>
    </system-out>
    <system-err/>
    </testsuite>
    </testsuites>

**Comment by plexus** [comment]
Hi @rascio, seems the problem is actually that you're two versions behind the current version of kaocha-junit-xml. I'm not 100% sure what the issue exactly is, but it works with `0.0-50`.

This must have happened because the version in the README is out of date. It's supposed to be automatically updated when releasing a new version, not sure why that didn't happen last time. I'll put out a new version today though so I'll make sure that gets updated.

I'd like to give some feedback on your `tests.edn` though

``` clojure
:cli-options {:capture-output false}
```

The config key `:kaocha/cli-options` is internal, you are not supposed to set it directly. It is used to communicate to plugins which command line options were provided. (also `:kaocha/cli-options` is not the same as `:cli-options`, so this really does nothing).

To disable output capturing, use ` :kaocha.plugin.capture-output/capture-output? false` (which you already did).

``` clojure
 :plugins [,,, :kaocha.plugin/capture-output]
```

This plugin is already included by default, no need to add it again.

``` clojure
 :reporter [kaocha.report/dots]
```

This is the default, so not really necessary.
