### ISSUE TITLE
XML output is different from lein test2junit

### ISSUE THREAD

**Issue by ondrs** [lambdaisland/kaocha-junit-xml#9]
Hi,
we are using a standard lein test on our Jenkins CI.
Jenkins can handle junit xml files so we are using `lein test2junit` plugin to generates them.
I’ve tried to replace the default lein test runner with kaocha. It works great except for junit files generated by kaocha’s junit xml plugin
The problem is how kaocha generates test suites and test case xml nodes.
A test suite in `lein test2junit` is a namespace in the test directory
In `kaocha junit xml` a test suite is a different concept https://cljdoc.org/d/lambdaisland/kaocha/1.0.641/doc/3-configuration#test-suites
The default test suite is `unit`.

When I run our tests `lein test2junit` it generates this XML
```xml
<testsuite name="ns.a">
  <testcase name="test-a"/>
  <testcase name="test-b"/>
  <testcase name="ns.b/test-a"/>
  <system-out>
    output from ns.a only
  </system-out>
</testsuite>
<testsuite name="ns.b">
  <testcase name="test-a"/>
  <system-out>
    output from ns.b only
  </system-out>
</testsuite>
```

but kaocha generates this

```xml
<testsuite name="unit">
  <testcase name="ns.a/test-a"/>
  <testcase name="ns.a/test-b"/>
  <testcase name="ns.b/test-a"/>
  <system-out>
    squashed output from every testcase... 
  </system-out>
</testsuite>
```

Is there a way how to configure kaocha to generate the same output as `lein test2junit` does?

**Comment by plexus** [comment]
Not really, your best best is to fork the plugin. It's common for projects that use Kaocha to include their own hooks and plugins if the defaults ones don't fit your exact use case.

**Comment by NoahTheDuke** [comment]
Is this stance still applicable? I too would love output like test2junit. I can take a swing at forking if no one else has tried

**Comment by plexus** [comment]
Can you elaborate on your need for this? What's cosuming the junit.xml? How does it show up in there? Share screenshots if possible.

If there's a clearly documented problem statement then we can consider proposals for solutions, working out things like what happens if you run multiple test suites in the same run, or if you run test suites of different types that don't have an intermediate testable layer (the way we have with namespaces in the clojure.test implementation).

The hardest part with junit.xml is that it's not properly standardized, and every tool deals with it slightly differently. What I'd really like to see is a knowledge base of how different tools generate junit.xml (with example syntax), and how they consume it (with screenshots).

**Comment by NoahTheDuke** [comment]
Actually, my apologies, I don't need this. I had my Gitlab CI misconfigured and thought this change in xml was the source of my issue.

**Comment by alysbrooks** [comment]
I think we're open to tweaking the format (or PRs that do the same), but I don't think simply diverging from a Leningen plugin is an issue. If you do have issues or want to improve compatability, feel free to open new issues or PRs.
